//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asyncify {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asyncify.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using await on the Task over synchronous blocking method GetResult().
        /// </summary>
        internal static string AsyncifyGetResultDescription {
            get {
                return ResourceManager.GetString("AsyncifyGetResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider awaiting Task &apos;{0}&apos;.
        /// </summary>
        internal static string AsyncifyGetResultMessageFormat {
            get {
                return ResourceManager.GetString("AsyncifyGetResultMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use await over synchronous method GetResult().
        /// </summary>
        internal static string AsyncifyGetResultTitle {
            get {
                return ResourceManager.GetString("AsyncifyGetResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using await on the Task over synchronous blocking property Result.
        /// </summary>
        internal static string AsyncifyResultDescription {
            get {
                return ResourceManager.GetString("AsyncifyResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider awaiting Task &apos;{0}&apos;.
        /// </summary>
        internal static string AsyncifyResultMessageFormat {
            get {
                return ResourceManager.GetString("AsyncifyResultMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use await over synchronous property Result.
        /// </summary>
        internal static string AsyncifyResultTitle {
            get {
                return ResourceManager.GetString("AsyncifyResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using await on the Task over synchronous blocking method Wait().
        /// </summary>
        internal static string AsyncifyWaitDescription {
            get {
                return ResourceManager.GetString("AsyncifyWaitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider awaiting Task &apos;{0}&apos;.
        /// </summary>
        internal static string AsyncifyWaitMessageFormat {
            get {
                return ResourceManager.GetString("AsyncifyWaitMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use await over synchronous method Wait().
        /// </summary>
        internal static string AsyncifyWaitTitle {
            get {
                return ResourceManager.GetString("AsyncifyWaitTitle", resourceCulture);
            }
        }
    }
}
